# Generated by Django 6.0.2 on 2026-02-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate_alter_orders_phone_alter_orders_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default=' '),
        ),
    ]
