# Generated by Django 6.0.2 on 2026-02-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='Timestamp',
            new_name='timestamp',
        ),
    ]
